version: '3.7'
services:

    # PHP Service
    app:
        image: php:8.1.6RC1-fpm-alpine
        container_name: "${DOCKER_CONTAINER_PREFIX:-laravel}_app"
        restart: unless-stopped
        tty: true
        volumes:
            - ./:/var/www
        networks:
            - appnet

    # Nginx Service
    nginx:
        image: nginx:alpine
        container_name: "${DOCKER_CONTAINER_PREFIX:-laravel}_nginx"
        restart: unless-stopped
        tty: true
        ports:
            - "${DOCKER_NGINX_PORT:-82}:80"
        volumes:
            - ./:/var/www
            - ./build/nginx/conf.d:/etc/nginx/conf.d:ro
        networks:
            - appnet

    #### More Services here


    mysql:
        image: 'mysql/mysql-server:8.0'
        container_name: "${DOCKER_CONTAINER_PREFIX:-laravel}_mysql"
        ports:
            - '${FORWARD_DB_PORT:-3303}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - ./:/var/lib/mysql
        networks:
            - appnet

# Networks
networks:
    appnet:
        driver: bridge
